[package]
name = "scoopie"
description = "Your favorite package manager"
version = "0.1.0"
authors = ["Rahul <basicfunc@gmail.com>"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/basicfunc/scoopie"
license-file = "LICENSE"
keywords = ["package", "package-manager"]
categories = ["command-line-utilities"]

[dependencies]
argh = "0.1.10"
digest = "0.10.7"
dirs = "5.0.1"
git2 = "0.17.2"
hex = "0.4.3"
md-5 = "0.10.5"
rayon = "1.7.0"
regex = "1.9.3"
serde = { version = "1.0.164", features = ["serde_derive"] }
serde_json = "1.0.99"
sha1 = "0.10.5"
sha2 = "0.10.7"
tempfile = "3.6.0"
thiserror = "1.0.41"
tokio = { version = "1.29.1", features = ["full"] }
toml = "0.7.5"
trauma = "2.2.3"
url = { version = "2.4.0", features = ["serde"] }
winreg = "0.50.0"
