[package]
name = "scoopie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.10"
dirs = "5.0.1"
git2 = "0.17.2"
