[package]
name = "scoopie"
description = "Your favorite package manager"
version = "0.1.0"
authors = ["Rahul <basicfunc@gmail.com>"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/basicfunc/scoopie"
license = "MIT"
license-file = "LICENSE"
keywords = ["package", "package-manager"]
categories = ["command-line-utilities"]

[dependencies]
argh = "0.1.10"
dirs = "5.0.1"
git2 = "0.17.2"
rayon = "1.7.0"
rusqlite = { version = "0.29.0", features = ["bundled-full"] }
serde = { version = "1.0.164", features = ["serde_derive"] }
serde_json = "1.0.99"
tempfile = "3.6.0"
thiserror = "1.0.41"
toml = "0.7.5"
