[package]
name = "scoopie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.10"
chrono = "0.4.26"
dirs = "5.0.1"
git2 = "0.17.2"
json_to_table = "0.5.0"
rayon = "1.7.0"
regex = "1.8.4"
rusqlite = { version = "0.29.0", features = ["bundled-full"] }
serde = { version = "1.0.164", features = ["serde_derive"] }
serde_json = "1.0.99"
tempfile = "3.6.0"
toml = "0.7.5"
